SU-SWS/stanford_ssp

- stanford_ssp.install
- stanford_ssp.module
> WMD->stanford_ssp migration path

- stanford_ssp.module
> Add redirect from sites/default/webauth/login to sso/login

- stanford_ssp.drush.inc
Looks like we passed the Ballmer Peak in writing this block of code...
> Fix notify option for drush ssp-au

- modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.pages.inc
- stanford_ssp.module
- Properly handles redirects for log in.
- End of June
- 1
1. Deploy this on https://sites576-dev.cardinalsites.stanford.edu/
2. Click the login link
3. Validate you end up on the right page.
> SITES-479: Preserve destination parameter.

- stanford_ssp.module
- Change to new production endpoint.
- Fix typo in cert names.
- Sometime in the next few months.
- 1/5 (I rationalize my denominators)
1. Check out this branch on either your local or on ACSF dev
2. Install a fresh site with either the Stanford profile or a Jumpstart
3. Log in with SAML and ensure you get your workgroup role mapping.
- All of them
- 
> workgroup production endpoint

- stanford_ssp.module
- Don't add unnecessary items to the menu.
- Yesterday
- 1
1. Review code
2. Check out branch
3. Install new site
4. Validate items do not show up in the `navigation` menu enabled or at all
5. Validate you can still log in.
> Adjust menu item types and remove testing endpoint.

- modules/stanford_saml_block/stanford_saml_block.module
- Adds a destination parameter to the login block link.
- Meh
- Low
2. Navigate to an interior page as an anonymous user
3. Click on the login link on the top right of the screen
4. Be logged in and back on to the page you were just at
- Everything
- SITES-725
> SITES-725: Found another avenue where destination was missing.

- stanford_ssp.module
- Changes the authorization restrictions to be additive
- This changes the behavior of the module but I think it better aligns with UX.
- For GUP Launch
- med-hi
1. Clone gup to local
2. Try logging in without your sunet id in the allowed sunets
3. Get denied
4. Check out this branch
5. Log in 
6. Have access
- Everything on SAML
- SITES-753
- SITES-993
> SITES-753: Change authorizations to OR from AND.

- composer.json
- src/Service/StanfordSSPAuthManager.php
- src/Service/StanfordSSPDrupalAuth.php
- stanford_ssp.info.yml
- stanford_ssp.services.yml
- tests/Unit/Service/StanfordSSPDrupalAuthTest.php
- Update service dependencies for latest simplesamlphp_auth module.
- ASAP
- HIGH
1. Update this module and simplesamlphp_auth
1. ensure it still functions correctly.
> Update for 3.1 contrib

- .circleci/config.yml
- README.md
- config/install/stanford_ssp.settings.yml
- config/schema/stanford_ssp.schema.yml
- src/EventSubscriber/StanfordSSPEventSubscriber.php
- src/Form/AddUserForm.php
- src/Service/StanfordSSPWorkgroupApi.php
- src/Service/StanfordSSPWorkgroupApiInterface.php
- stanford_ssp.install
- tests/modules/stanford_ssp_test/stanford_ssp_test.info.yml
- tests/modules/stanford_ssp_test/stanford_ssp_test.module
- tests/src/Kernel/Commands/StanfordSspCommandsTest.php
- tests/src/Kernel/EventSubscriber/StanfordSSPEventSubscriberTest.php
- tests/src/Kernel/Form/AddUserFormTest.php
- tests/src/Kernel/Form/AuthorizationsFormTest.php
- tests/src/Kernel/Form/LocalLoginFormTest.php
- tests/src/Kernel/Form/RoleSyncFormTest.php
- tests/src/Kernel/Routing/RouteSubscriber/RouteSubscriberTest.php
- tests/src/Unit/Plugin/Block/SamlLoginBlockTest.php
- tests/src/Unit/Service/StanfordSSPAuthManagerTest.php
- tests/src/Unit/Service/StanfordSSPDrupalAuthTest.php
- tests/src/Unit/Service/StanfordSSPWorkgroupApiTest.php
- Added circleci to run tests
- soon
- low
1. review test results
1. we'll have to increase code coverage to get it to pass.
> added circleci

- stanford_ssp.module
- Removed tabs on `/user/login` page
- added text to be styled for portal page
- 2/12
- medium
see https://github.com/SU-SWS/stanford_basic/pull/124
https://github.com/SU-SWS/stanford_profile/pull/82
https://github.com/SU-SWS/stanford_basic/pull/124
> D8CORE-1024 Adjusted login screen to improve portal style

- src/Form/RoleSyncForm.php
- src/Service/StanfordSSPWorkgroupApi.php
- src/Service/StanfordSSPWorkgroupApiInterface.php
See https://github.com/SU-SWS/stanford_profile/pull/140.
Probably not needed but can't hurt.
> D8CORE-1511: Change role mapping for stanford_ssp from itservices:webservices to uit:sws

- src/Form/RoleSyncForm.php
- src/Service/StanfordSSPWorkgroupApi.php
- src/Service/StanfordSSPWorkgroupApiInterface.php
- tests/src/Kernel/Form/RoleSyncFormTest.php
- tests/src/Unit/Service/StanfordSSPWorkgroupApiTest.php
- Added validation to check if the workgroup is private.
- 3/27
- low
1. create a private workgroup via workgroups.stanford.edu
1. try to add that workgroup to `/admin/config/people/simplesamlphp_auth/sync`
1. verify you get an error.
> D8CORE-1545 Added validation to check for public workgroups

- src/Form/RoleSyncForm.php
- src/Service/StanfordSSPWorkgroupApi.php
- tests/modules/stanford_ssp_test/stanford_ssp_test.info.yml
- tests/src/Kernel/Form/LocalLoginFormTest.php
- tests/src/Kernel/Form/RoleSyncFormTest.php
- tests/src/Unit/Service/StanfordSSPWorkgroupApiTest.php
- Updated phpunit tests so they will pass on phpunit 8 with drupal 9
- whenever
- low
> Adjusted tests to pass on D9

- stanford_ssp.module
- Removed a stray random character we don't want.
- You can't see it in the "Files Changed" so heres what the change is:
```
diff --git a/stanford_ssp.module b/stanford_ssp.module
index 16a6b4d..36c9411 100644
--- a/stanford_ssp.module
+++ b/stanford_ssp.module
@@ -54,7 +54,7 @@ function stanford_ssp_form_user_login_form_alter(&$form, FormStateInterface $for
$form['intro_text'] = [
'#type' => 'html_tag',
'#tag' => 'p',
-      '#value' => t('Welcome back! <U+2028>Login to access your website'),
+      '#value' => t('Welcome back! Log in to access your website'),
'#weight' => -998,
];
```
- :shrug: 
- low
1. review the change. nothing to test.
> Removed random unwanted character

- config/install/stanford_ssp.settings.yml
- config/schema/stanford_ssp.schema.yml
- src/Form/AuthorizationsForm.php
- src/Service/StanfordSSPWorkgroupApi.php
- stanford_ssp.install
- stanford_ssp.module
- tests/src/Kernel/Form/AuthorizationsFormTest.php
- Replace "Whitelist" with "Allowed"
- This has implications on all of our Drupal 8/9 stacks
- asap
- high
2. run database updates
3. verify you can still log into the site without any errors.
> D8CORE-3953 Refactor to replace "whitelist" with "allowed" in config settings

- src/EventSubscriber/StanfordSSPEventSubscriber.php
- pass Query parameters back through after logging in via saml.
- 4/8
- medium
1. 
> HSD8-1027 Pass query parameters after loggin in via saml

- stanford_ssp.module
- Check for attribute existance
> D8CORE-000: Check for attribute existence on user login

- config/install/stanford_ssp.settings.yml
- config/schema/stanford_ssp.schema.yml
- src/Form/AuthorizationsForm.php
- stanford_ssp.install
- stanford_ssp.module
- tests/src/Kernel/Form/AuthorizationsFormTest.php
- Add configurable restriction based on the affiliation.
- 6/3
- medium
1. Follow steps in https://github.com/SU-SWS/stanford_profile/pull/424
> D8CORE-4339 Allow restriction based on the person's affiliation to the university

- stanford_ssp.module
- Revert name alter hook which uses `su_display_name` field value to fix authored by bug
4. Verify...
- Other PRs
- Anyone who should be notified? (`@mention` them here)
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML …
> Revert su_display name_later hook.

- .circleci/config.yml
> test php 8

- composer.json
- src/Form/AddUserForm.php
- stanford_ssp.module
- tests/src/Kernel/Form/AddUserFormTest.php
- tests/src/Unit/Plugin/Block/SamlLoginBlockTest.php
- tests/src/Unit/Service/StanfordSSPWorkgroupApiTest.php
> Replace deprecated functions

- config/install/stanford_ssp.settings.yml
- config/schema/stanford_ssp.schema.yml
- src/EventSubscriber/StanfordSSPEventSubscriber.php
- stanford_ssp.info.yml
- stanford_ssp.install
- stanford_ssp.services.yml
- tests/src/Kernel/Commands/StanfordSspCommandsTest.php
- tests/src/Kernel/EventSubscriber/StanfordSSPEventSubscriberTest.php
- tests/src/Kernel/Form/AddUserFormTest.php
- tests/src/Kernel/Form/AuthorizationsFormTest.php
- tests/src/Kernel/Form/LocalLoginFormTest.php
- tests/src/Kernel/Form/RoleSyncFormTest.php
- tests/src/Kernel/Routing/RouteSubscriber/RouteSubscriberTest.php
> Add settings to exclude 403 paths that are redirected

- src/EventSubscriber/StanfordSSPEventSubscriber.php
> D8CORE-6510 Redirect user creation if local login is disabled

- src/EventSubscriber/StanfordSSPEventSubscriber.php
> Fixed redirect route for adding user
