stanford_ssp.module

This is to prevent an "Access Denied" error on a site where a user has already successfully logged in over https but when returning to the site over http gets redirected to the log in page.
*To test:*
It will be hard to test unless you have the SimpleSAMLPHP set up and pointed to the anchorage IDP on your local. I've pushed the code to http://hsbi.stanford.edu/ so you can try the following there.
1. Navigate to http://hsbi.stanford.edu/operational-reports
2. Confirm that you are logged in and on the Operational Reports page over https://
3. Open up a new tab or window and navigate to http://hsbi.stanford.edu/operational-reports
4. Confirm you are still logged in and on the Operational Reports page over https://
You will fail on the last step and be shown an Access Denied error on …

HSDO-510: HTTP/HTTPS redirect and redirect on login functionality

---

.codeclimate.yml
modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.api.php
modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.inc
modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.pages.inc
stanford_ssp.admin.inc
stanford_ssp.install

- Upgrade from old 'n' busted to new hotness
- 9.8.17
- How critical is this PR on a 1-10 scale? 10
- As we move to SAML authentication, we want this.
1. Install a site with the 1.x branch
2. Check this branch out
3. Run `drush updb`
4. Verify that your settings from the contrib `simplesamlphp_auth` are carried over
- Oh, probably eventually everything in D7
- https://stanfordits.atlassian.net/browse/SITES-20
1. This does not address an upgrade path from earlier 2.x versions of `stanford_ssp/stanford_simplesamlphp_auth`, and indeed would likely break them. Given that we only have two sites using that version, it may be simplest just to manually update the `schema_version` for those two sites
2. I expect there will be some discussion around this PR
3. I will do further testing of this on …

SITES-20: Upgrade path for stanford_ssp/stanford_simplesamlphp_auth from simplesamlphp_auth

---

modules/stanford_saml_block/stanford_saml_block.module
modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.inc
modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.install
modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.module
stanford_ssp.admin.inc
stanford_ssp.drush.inc
stanford_ssp.install
stanford_ssp.module

A few things are changed:
the custom block wouldn't appear on the configuration page, so I couldn't update the link text nor the title. Changed the default region from 0 to -1 to make it appear.
the custom block didn't have a save function for the link text
I added a switch, disabled by default for the reformatting of entitlements. I wasn't sure if there was a need for configuration of what characters to replace with what others, so I left it simple for now.
Using drush sspwmd, the permissions from SUNet User are copied over to SSO User
There was a dry-run option that wasn't working, not implemented
Updated the default install directory as discussed

Block Fixes

---

modules/stanford_saml_block/stanford_saml_block.module
modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.inc
modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.install
modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.module
modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.pages.inc
stanford_ssp.admin.inc
stanford_ssp.drush.inc
stanford_ssp.install
stanford_ssp.module

- Adds workgroup API role evaluation
- Adds ability to toggle between workgroup formats ":" vs "_"
- End of sprint?
- 6 out of 10?
1. On your local, check out the latest of the socorro branch for acsf_cardinald7 and this branch
2. Ensure you have a jsv or other jumpstart site with the `acsf` itasks build so that stanford_ssp module is enabled
3. Log in as an administrator and navigate to /admin/config/stanford/stanford_ssp/role-mappings
4. Add an administrator workgroup mapping for itservices:webservices
5. Select workgroup api radio as the validation source
6. Enter the server path to the cert `buws-cardinald7-test.cert`
7. Enter the server path to the key `wkgrp-test.key`
8. Manually set the workgroup api to the UAT server via drush `drush vset stanford_ssp_workgroup_api_endpoint …

SITES-616: Add workgroup API role mapping option

---

stanford_ssp.admin.inc
stanford_ssp.drush.inc
stanford_ssp.module

- Turns out the `--notify` option is reserved for drush
- Changed command option to `--notify-user` 
- SAML warning in watchdog is just debugging messaging and nothing to worry about.
- Whenever
- 1-10? 1
1.  Check out this branch
2. Create a new user using `drush ssp-au sunetid --notify-user=true`

SITES-492: Notify user on drush ssp-au command.

---

README.md
stanford_ssp.module

- Provide a migration path where we grant the "SUNet User" role if we are migrating from WMD
- Document `drush sspwmd`
- When you can get to it
- How critical is this PR on a 1-10 scale? 2/10
1. Grab a DB dump from a site with WMD where you do **not** have a user account
2. Install `stanford_ssp-7.x-2.x`
3. Log in
4. See that you do **not** get the "SUNet User" role
5. Restore from DB dump
6. Check out this branch
7. Log in
8. See that you do **not** get the "SUNet User" role
9. Restore from DB dump
10. Check out this branch
11. Run `drush sspwmd`
12. Log in
13. See that you **do** get the "SUNet User" role
14. Review the updated README for Migrating from WMD and check for inaccuracies or blatant lies
- Does this PR impact any particular projects, products, or modules? ACSF
- JIRA ticket: …

Grant SUNet User role conditionally

---

stanford_ssp.module

- Fixes issue with creating a new user.
- Soon as you can
- 7/10
1. Spin up a site on the 7.x-2.x branch of this module
2. Log in and try to create a local user and a SSO user. Get error on both.
3. Check out this branch.
4. Repeat step 2 but with success
- SITES-676

SITES-676: Prevent duplicate values when creating new user.

---

stanford_ssp.module

- Allow users to log in when site is in maintenance mode
- The sooner you merge this, the sooner I get to stop dealing with SNOW tickets from a specific user who keeps locking himself out of his site
- How critical is this PR on a 1-10 scale? 3/10
1. Create an SSO account for yourself that has a privileged role, with the permission to access the site in maintenance mode
2. Check out 7.x-2.x
3. Put the site in maintenance mode
4. Log out
5. Try to log in at `sso/login`
6. Fail
7. Check out this branch
8. Try to log in at `sso/login`
9. Succeed
- SAML authentication
- JIRA ticket: https://stanfordits.atlassian.net/browse/SITES-924

SITES-924: access sso/login in maintenance mode

---

modules/stanford_saml_block/stanford_saml_block.context.inc
stanford_ssp.module

- Swap out stanford_saml_block for webauth block and disable the context by default.
- By replacing the webauth block for the saml block in the DB table we will get everywhere the webauth block was placed using core blocks.
- Disables a not-so-good context by default. Never liked that placement anyhow.
- ?
- Lower
2. (on local) sync people site `sheamck`'s database down
3. Run `drush rr`
4. Run `drush updb -y`
5. Run `drush en stanford_ssp -y`
6. Run `drush sspwmd -y`
8. Clear caches and view the home page. SAML block should be in left sidebar. 
- Migration
- SITES-892

SITES-892: Webauth upgrade path fix for block placement 

---

modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.inc
modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.module
stanford_ssp.admin.inc
stanford_ssp.module

- Better error handling for bad rules
- Better logging and handling for bad API requests
- Handling for `stanford:*` type workgroup maps. These don't work in the API.
- Force SAML attribute affiliation mapping to handle the `stanford:*` mappings instead. 
- SAML attribute affiliation mapping on user register.
- For Greg
- Ask Greg
1. Copy dennylab to a test environment
2. Log in with sso/login and view logs
3. See PHP errors and warnings 
4. Check out this branch
5. Log out and log back in
6. See no more PHP errors.
7. Delete user account
8. Log out
9. Log back in
10. Validate Affiliation roles have been assigned
- All of them
- SOE Migration
- @boznik 
- @jbickar 
- SITES-784

SITES-784: Better error handling. Skip stanford:* type workgroups.

---

modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.module

- Fix bug where workgroups with underscores in them trigger an "Invalid workgroup format" error
- When does this need to be merged by? ASAP
- How critical is this PR on a 1-10 scale? 3/10
1. Verify that this code is checked out on ACSF `dev`
2. Log in to https://inc00811537workgroupmapping-dev.sites.stanford.edu/sso/login
3. Verify that you get the "Underscore" role
(I already mapped `~jbickar:i_a` to the "Underscore role and added you and me to that workgroup.)
- Does this PR impact any particular projects, products, or modules? ACSF
- JIRA ticket: https://stanfordits.atlassian.net/browse/SITES-1109

SITES-1109: Workgroups with underscores are invalidated

---

src/Form/AddUserForm.php

- When role_delegation is enabled, users should only be able to add roles that they have permission to.
- If role delegation is not enabled, allow all roles.
- asap
- kinda high. security implications since site managers could add a user with administrator role.
1. enable role_delegation and configure for a role
1. go to the user add form as a user with limited role add permissions
1. verify they can not add a user with an administrator role.
- Humsci right now, all in the future

HSD8-613 If role_delegation module is enable, limit which roles a user can add in the saml user add form.

---

src/Service/StanfordSSPAuthManager.php
stanford_ssp.services.yml
tests/Unit/Service/StanfordSSPDrupalAuthTest.php

- When no `mail` attribute is passed, build an email from the uid
- asap
- High. its a blocker for a user on williams in H&S
1. run unit tests.

Decorate service to stop fatal error when mail attribute isnt available

---

modules/stanford_saml_block/stanford_saml_block.module
modules/stanford_simplesamlphp_auth/stanford_simplesamlphp_auth.module
stanford_ssp.module

- Add `rel="nofollow"` to all `sso/login` links.
- Sometime
- How critical is this PR on a 1-10 scale? 3/10
- Affects all sites and should cut down on drupal bootstraps
1. Go to https://20190620jsa-dev.sites.stanford.edu/ as an anonymous user
2. Check that the "SUNetID Login" link in the global header has a `rel="nofollow"` attribute
3. Go to https://20190620jsa-dev.sites.stanford.edu/user
4. Check that the "Log in with your SUNetID" link has a `rel="nofollow"` attribute
- Everything that uses stanford_ssp
- Anyone who should be notified? ( @pookmish )

rel=nofollow

---

src/Plugin/Block/SamlLoginBlock.php
stanford_ssp.module

- Add `rel="nofollow"` attribute to login link
- Sometime
- How critical is this PR on a 1-10 scale? 2/10
- Cuts down on extraneous robot requests (we hope)
2. Go to `/user`
3. Verify that the SAML login link has a `rel="nofollow"` attribute
- D8 sites
- Other PRs: #73 
- Anyone who should be notified? ( @sherakama )

Add rel="nofollow" attribute

---

src/Form/RoleSyncForm.php
tests/src/Kernel/Form/RoleSyncFormTest.php

- Allow user to enter what attributes to use for role mapping
- End of sprint 9/27
- low
1. Checkout this branch
1. navigate to `/admin/config/people/simplesamlphp_auth/sync`
1. add a workgroup by leaving the attribute empty.
1. validate it uses `eduPersonEnttitlement` as the attribute
1. add a workgroup by setting the attribute to some value
1. validate it uses the entered data as the attribute.

D8CORE-265 Allow use of other saml attributes

---

stanford_ssp.routing.yml
tests/src/Kernel/Form/AuthorizationsFormTest.php
tests/src/Kernel/Routing/RouteSubscriber/RouteSubscriberTest.php
tests/src/Unit/Plugin/Block/SamlLoginBlockTest.php

- For D8CORE-1118, we want a redirect route from /sso/login, which is the traditional SSO url, to /saml_login, which is the D8 version of the SSO url.  We also don't want to disturb any other links to the D8 version.
- Fix version is RC-2 for the D8CORE project
- not critical.
1. In a D8 instance, with SSO configured,
2.  Visit `/sso/login`
2.  Observe that you are redirected to `/saml_login`, and then on to the SSO sign in page.
- Only affects the `stanford_ssp` module.
- Depends on the `simplesamlphp` module
- D8Core-1118
- no.
- I don't believe so.
* Site? - nope
* Product? - nope
* Stanford? - it's generalized to Stanford D8 generally.
- no changes to forms.
- nope.
- part of the point was to normalize the route naming to match our convention.
- no additional documentation required
- …

Added a redirection route from /sso/login to /saml_login

---

.circleci/config.yml
src/Form/RoleSyncForm.php
tests/src/Unit/Service/StanfordSSPAuthManagerTest.php
tests/src/Unit/Service/StanfordSSPDrupalAuthTest.php

- Fixed validation error if the cert and key are overridden via settings.php.
- Fixed logic error when deleting the last role mapping. It wasn't actually deleting it.
- 2/12
- low
1. on /admin/config/people/simplesamlphp_auth/sync add and delete role mapping
1. verify it works as expected.

D8CORE-1243 Fix role mapping form ajax

---

src/Form/LocalLoginForm.php

- use the right config for the form value
- some day
- low
1. on `/admin/config/people/simplesamlphp_auth/local` validate the checkbox "Hide local login form on the user page." works as expected

D8CORE-1263 Fix config form

---

.circleci/config.yml
.github/workflows/release.yml
CHANGELOG.md
README.md
src/Form/RoleSyncForm.php
src/Service/StanfordSSPWorkgroupApi.php
src/Service/StanfordSSPWorkgroupApiInterface.php
stanford_ssp.info.yml
tests/src/Kernel/Form/RoleSyncFormTest.php
tests/src/Unit/Service/StanfordSSPWorkgroupApiTest.php

- Validate that the workgroups entered are public when using the workgroup API
- Users won't be able to enter private workgroups and be confused when the role mapping doesn't work.
- Deploy & Clear cache 
- None
Changes:
https://github.com/SU-SWS/stanford_ssp/compare/release-8.1.4

Release 8.1.4

---

stanford_ssp.module

- Allowing workgroups with one member in d7 to have their role map.
- TBD
- low
1. Setup local to login with saml on d7.
2. Check out this branch
3. Map administrator role to a workgroup with only one member
4. Verify that upon login with the one member in the workgroup, the role is assigned.
5. Add another member to the workgroup and verify that upon login, the role is still assigned.

DEVOPS-261: modified array if only one member in workgroup

---

stanford_ssp.admin.inc

- Matching default certs with actual name
- Soon
- low
2. Navigate to role mapping and verify cert names match actual certs

DEVOPS-291: Changed cert names so that defaults matched actual certs

---

stanford_ssp.module

- The logs report the following warning:  `ini_set(): A session is active. You cannot change the session module's ini settings at this time in stanford_ssp_force_https() (line 254 of /mnt/www/html/swssoe/docroot/sites/all/modules/stanford/stanford_ssp/stanford_ssp.module`.
- The problem. Another Stanford module by the name of Webauth has already called `[ini_set()](https://github.com/Stanford/WMD/blob/7894e24736471773ab19f27698fafed5f7830079/webauth.module#L24)` method, which is probably what makes ini_set() in the other module create the warning. 
- Solution, while it's possible to remove `ini_set` (cookie_session.secure is already set to '1') from the stanford_ssp module, I'm not sure why it was placed there in the first place. Leaving it in, but wrapped around a condition that checks …

SOEOP-402 - Added conditional to prevent error.

---

CHANGELOG.md
README.md
config/install/stanford_ssp.settings.yml
config/schema/stanford_ssp.schema.yml
src/Service/StanfordSSPWorkgroupApi.php
stanford_ssp.install
tests/src/Kernel/Form/RoleSyncFormTest.php
tests/src/Unit/Service/StanfordSSPWorkgroupApiTest.php

- Upgrade workgroup API to V2
- As far as i know, all of our workgroup api connections use the same cert so this should just be a normal upgrade.
- If anyone (earth) might be using this module AND the workgroup api, it will verify the certs during the upgrade process and throw an error if it fails.
- 4/28
- medium
2. re-install a site and log in using saml
3. verify you still get the expected role from the role mapping.

D8CORE-4083 Use API V2 for the new workgroup API

---

src/Form/AddUserForm.php
stanford_ssp.links.action.yml

- Changed button labels from "Add SSO User" to "Add SUNetID User"
- 5/6/21
- medium
1. Checkout this branch.
2. Clear your drupal caches.
3. go to `/admin/people/create`. Verify the button at the top says, "Add SUNetID User".
4. Click the button.
5. on the Add SAML User page, make sure the button at the bottom says, "Add SUNetID User".

D8CORE-4129: changed labels for new sso user buttons

---

composer.json
src/EventSubscriber/StanfordSSPEventSubscriber.php
tests/src/Kernel/EventSubscriber/StanfordSSPEventSubscriberTest.php

- The contrib module actually expects the parameter `ReturnTo`, not `destination`. This fixes an issue when on an intranet site and attempt to go to the home page. Before, the destination failed to validate in the controller and so it fell back to the `/user` path. This passes the correct parameter with the expected string so that if a user lands on an intranet home page, they will log in and then go to the home page instead of their user page.
- https://git.drupalcode.org/project/simplesamlphp_auth/-/blob/8.x-3.x/src/Controller/SimplesamlphpAuthController.php#L150
- 9/15
- medium
1. Checkout this branch
2. configure your site to be intranet `drush sset stanford_intranet 1; drush cr`
3. load your home page in a browser
4. log in and verify you land back on the home page after logging in. …

Fixed the destination path after saml login

---

composer.json
config/install/stanford_ssp.settings.yml
config/schema/stanford_ssp.schema.yml
src/Commands/StanfordSspCommands.php
src/EventSubscriber/StanfordSSPEventSubscriber.php
src/Form/RoleSyncForm.php
src/Service/StanfordSSPAuthManager.php
src/Service/StanfordSSPWorkgroupApi.php
src/Service/StanfordSSPWorkgroupApiInterface.php
stanford_ssp.info.yml
stanford_ssp.install
stanford_ssp.module
tests/src/Kernel/Form/RoleSyncFormTest.php
tests/src/Unit/Service/StanfordSSPDrupalAuthTest.php
tests/src/Unit/Service/StanfordSSPWorkgroupApiTest.php

- Expand the existing user lookup to prevent unwanted user duplication
- More existing user lookup to prevent `simplesamlphp_auth_[sunet]` error.
- Not sure how the error even comes about, but this fixes it.
- High
0. USE THE MAIN BRANCH FIRST
1. log into a site using saml
2. alter the database `drush sqlq 'UPDATE authmap a INNER JOIN users_field_data u ON a.uid = u.uid SET a.authname = u.name'`
3. log out of the site `/user/logout`
4. log back into the site.
5. view the error.
6. Delete the bad account `drush ucan 'simplesamlphp_auth_[sunetid]' --delete-content -y`
7. Checkout this branch
8. repeat the process but on this branch
9. verify you don't see the error.

Expand the existing user lookup to prevent unwanted user duplication
